CODE_OF_CONDUCT.md, SECURITY.md, src/bin/rgb/command.rs
=> Fix spelling

README.md
the link was previously pointing to pixel-related struct
=> fixed crates.io link

src/pay.rs
=> Select correct assignment name

Cargo.lock, Cargo.toml, src/lib.rs, src/resolvers/mod.rs
Fixes some WASM compilation issues in #131
=> WASM fixes.

src/resolvers/electrum.rs, src/resolvers/esplora_blocking.rs
=> replace panic with error for unsupported layer1

Cargo.lock, Cargo.toml, cli/src/command.rs, src/pay.rs
Counterpart to https://github.com/RGB-WG/rgb-schemata/pull/36 and https://github.com/RGB-WG/rgb-std/pull/162
=> Update to match the refactored interfaces

Cargo.lock, Cargo.toml, cli/Cargo.toml
The final check before the release
=> Release v0.11.0-beta.5

Cargo.lock, Cargo.toml, cli/src/command.rs, psbt/src/lib.rs, src/pay.rs, src/resolvers/any.rs, src/resolvers/electrum.rs, src/resolvers/esplora_blocking.rs, src/runtime.rs
Counterparty for:
- https://github.com/RGB-WG/rgb-core/pull/236
- https://github.com/RGB-WG/rgb-std/pull/183
=> Move asset tags to genesis

src/resolvers/electrum_blocking.rs
as discussed on telegram, this PR implements @adambor proposal to add a safety margin
=> electrum: add safety margins for tx height check

Cargo.lock, Cargo.toml, cli/src/command.rs, src/descriptor.rs, src/lib.rs
=> Save wallet data when modified

src/pay.rs
=> Support for UDA payments

Cargo.lock, Cargo.toml, cli/src/command.rs, src/pay.rs
Counterparts for https://github.com/RGB-WG/rgb-std/pull/203
=> Use new Pay2Vout standard library feature

cli/src/command.rs
Built on top of https://github.com/RGB-WG/rgb/pull/203 fixing some issues with it
=> Display other state types in cli

cli/src/command.rs
print data, attachment, rights state
=> print data attachment rights state

src/descriptor.rs
Addresses part of https://github.com/BP-WG/bp-wallet/issues/52
=> Descriptor: fix encofced keychains value for Tapret

Cargo.lock, Cargo.toml, src/indexers/any.rs
Counterpart for https://github.com/RGB-WG/rgb-std/pull/239
=> Update to use enum-based PubWitness type from std lib

Cargo.lock, Cargo.toml
Closes #230 
Requires https://github.com/BP-WG/bp-wallet/pull/59
=> Support finalization and extraction for PSBTs

cli/src/command.rs
Closes #239
Also related: https://github.com/BP-WG/bp-std/pull/41
CC @zoedberg @nicbus
=> Fix version used in printing out PSBT

.github/workflows/build.yml, Cargo.lock, Cargo.toml, cli/src/args.rs, cli/src/command.rs, src/errors.rs, src/pay.rs, src/wallet.rs, src/wrapper.rs
Counterpart for https://github.com/BP-WG/bp-wallet/pull/66 and https://github.com/RGB-WG/rgb-std/pull/251
=> Use new StoreProvider APIs

cli/src/args.rs, src/runtime.rs
certain scenarios require manually tweak the PSBT
=> chore: make compose_psbt as public
