RGB-WG/rgb

- .gitignore
- src/bin/rgb/main.rs
When I tried use rgb-cli with `--electrum localhost:50001 --chain regtest` options, the follow error occurs:
```
thread 'main' panicked at 'no default server is known for regtest, please provide a custom URL', src/wallet.rs:124:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I found the reason here: https://stackoverflow.com/a/56726618
This PR fix that!
> fix: get correct server parameters

- Cargo.toml
- src/wallet.rs
this small PR adds a default electrum resolver for the `Regtest` network in the `default_resolver` function
> add default resolver for regtest

- .github/workflows/build.yml
- .github/workflows/codecov.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
- Cargo.lock
- Cargo.toml
- src/bin/rgb/command.rs
This PR adds the `set-host` command to set `opret`/`tapret` host, if needed.
This is intended to be called by a user that has prepared a PSBT with an output ready for the commitment but needing to set it as a host, via CLI.
This comes from (and depends on) [rgb-wallet PR #46](https://github.com/RGB-WG/rgb-wallet/pull/46), which initially did the same in the `pay` command but now only makes `opret` and `tapret` modules public.
> add set-host command

- src/wallet.rs
This PR intend implement the `ResolverHeight` with combination of two electrum methods: **get_transaction**  and **batch_script_get_history**.
> Resolver Height (get by spent script)

- .github/workflows/build.yml
- src/bin/rgb/command.rs
- src/bin/rgb/main.rs
- src/lib.rs
- src/runtime.rs
- src/wallet.rs
> Remove required electrum resolver

- .github/workflows/build.yml
- .github/workflows/codecov.yml
- .github/workflows/lint.yml
- Cargo.lock
- Cargo.toml
- src/bin/rgb/command.rs
- src/bin/rgb/main.rs
- src/descriptor.rs
- src/runtime.rs
- src/wallet.rs
> Release v0.10.1

- src/bin/rgb/command.rs
> Fix force accept of invalid consignments

- Cargo.lock
- Cargo.toml
- cli/src/command.rs
- src/pay.rs
- src/runtime.rs
The PR for the first time provides an ability for a runtime to reconstruct operation history for any fungible asset (not just RGB20, but under any interface) out of stash data (plus wallet information) - and print it out via cli command `fungible-history`.
> Fungible operation history

- src/pay.rs
This PR fixes #105 by allowing `construct_psbt()` to continue execution instead of returning an error if no tapret output is found.
> fix opret support

- Cargo.lock
- Cargo.toml
- src/resolvers/electrum.rs
- src/resolvers/mod.rs
This PR closes https://github.com/RGB-WG/rgb/issues/95
Retrieving the block height of a transaction was not trivial (wondering why the electrum protocol doesn't expose such a feature), therefore the implementation of `resolve_anchor` is not as simple and readable as the esplora version. Anyway I tested this on rgb-lib and it seems to work fine.
Also, I was not sure about the naming, should I call the module/feature `electrum_blocking` (similar to current `esplora_blocking`) or is it ok to call it just `electrum`?
> add electrum resolver

- src/resolvers/electrum.rs
Sorry to signal this bug just some days after opening the PR that implemented this, but I've just found a test case that triggered this bug.
The fix allows the `resolve_anchor` method to detect 0-conf transactions.
> fix electrum Resolver

- src/pay.rs
This is a copy of https://github.com/RGB-WG/rgb/pull/112 which was merged into an incorrect branch
> Fix opret support in construct_psbt()

- Cargo.lock
- Cargo.toml
- cli/src/command.rs
Pls pay attention to the new `reconstruct` cli command, hidden from the normal documentation
> Complete YAML inspection for consignments and stash

- Cargo.lock
- Cargo.toml
- src/resolvers/electrum.rs
This PR replaces the electrum-client and bitcoin crates with bp-electrum. Rationale: https://github.com/BP-WG/bp-wallet/pull/19#issuecomment-2002402743
Not sure this should be merged before the bp-electrum crate is released on crates.io, @dr-orlovsky maybe we should release that and then update and merge this PR?
> replace electrum-client with bp-electrum

- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/src/args.rs
- src/resolvers/any.rs
- src/resolvers/mod.rs
- src/runtime.rs
This PR completes support for electrum.
`rgb-runtime` now uses either electrum or esplora as a resolver, using the same rules as in `bp-wallet`/`bp-util`.
This is in draft as it depends on https://github.com/BP-WG/bp-wallet/pull/19.
> complete electrum support

- Cargo.lock
- Cargo.toml
- psbt/src/lib.rs
- src/pay.rs
Closes #117 and https://github.com/BP-WG/bp-wallet/issues/14
@Matrix-Zhang this fixes an issue you have reported, can you confirm that it works with this code?
> Pay: fix duplicated PSBT inputs

- Cargo.lock
- Cargo.toml
- cli/src/command.rs
- psbt/src/lib.rs
- psbt/src/rgb.rs
Opret and tapret combined result in two bundles in witness transaction. This PR solves the way such situations are handled, also using fixes on double-commitment schemes from RGB core and standard libraries.
Counterpart to:
- https://github.com/RGB-WG/rgb-core/pull/232
- https://github.com/RGB-WG/rgb-std/pull/180
> Support up to two bundles per witness PSBT

- src/pay.rs
I've found a bug while doing transfers between an opret wallet (using rgb-lib) and a tapret wallet (using rgb-wallet). In detail I've:
1. issued a contract with the opret wallet
2. sent some assets from the opret to the tapret wallet
- in witness
- the sender defined an opret seal
3. sent some assets back from the tapret to the opret wallet
- with a blinded UTXO
- requesting an opret seal
The second transfer will have in input an opret seal and will define 2 seals, one opret (for the receiver) and one tapret (for the RGB change), therefore it will need to create an opret anchor.
This transfer fails (when calling the [`pay` method](https://github.com/RGB-WG/rgb/blob/master/src/pay.rs#L161)) with the error `Completion(TapretKey(NoCommitment))`.
Investigating this, I've noticed that the call …
> add tapret tweak only when necessary

- psbt/src/lib.rs
**Description**
This PR fixes the addition of the "rgb input consumer" property only for inputs that are part of RGB transitions.
I got this bug after executing consecutive transfers, and to avoid "dust transaction", I started mixing different terminal derivations (i.e., tapret with bitcoin, opret with change, etc..)
> Mark as rgb-consumer only transition inputs

- Cargo.lock
- cli/src/args.rs
- src/resolvers/any.rs
- src/resolvers/electrum_blocking.rs
- src/resolvers/esplora_blocking.rs
Closes https://github.com/RGB-WG/rgb/issues/193.
This PR implements a `check` method for the resolvers, which makes sure the provided resolver is for the correct network and, for the electrum server it checks the necessary functionality (verbose transactions support) is there. I've taken inspiration from what we do in rgb-lib.
Note: in rust-bitcoin there's a method of the block header, `block_hash`, that easily gives you the block hash for the header. I didn't find this method in the header from bp so for simplicity I've just implemented the hash calculation in the electrum check method, but @dr-orlovsky if you agree I can implement the method and then subsitute that here, let me know.
> resolver: implement check

- Cargo.lock
- Cargo.toml
- cli/src/args.rs
- src/resolvers/any.rs
With this PR we allow RGB users to set a custom configuration for the resolvers. This feature could be useful especially for mobile clients, where the default timeout (30 seconds) could be too high.
Since electrum and esplora crates have different ways to instantiate a new client I've also made this https://github.com/BP-WG/bp-esplora-client/pull/5 to add a `Config` to esplora, making it more similar to the electrum client. For this reason this PR is in draft, once that will be merged I'll revert the patch and undraft this.
Note: this PR also fixes the build (which was broken due to a force push in bp-core).
> make resolvers configurable

- cli/src/command.rs
As discussed in #209, this PR converts fungible allocation values into human-readable integers.
> report fungible values in human-readable form

- src/resolvers/electrum_blocking.rs
In the PR https://github.com/RGB-WG/rgb/pull/198, specifically in the commit https://github.com/RGB-WG/rgb/pull/198/commits/eeb9d557746d3aa1f6763508b6ca1ea759f8d1d8, the refactor removed an important part in the `resolve_height` method of the electrum resolver. The check of `No such mempool or blockchain transaction` error was there to detect offchain transactions. I've re-added the check so that know the behavior of the electrum resolver is the same of the esplora one.
> fix electrum resolve_height for offchain TXs

- Cargo.toml
This PR removes the default features from bp-esplora, only keeping `blocking`.
Conbined with https://github.com/BP-WG/bp-wallet/pull/42, this has the effect of dropping lots of dependencies that were in fact unused.
> keep only blocking feature for bp-esplora

- Cargo.toml
implementation: https://github.com/RGB-WG/RFC/issues/9
> make rgb-std's fs feature optional in rgb

- Cargo.lock
- Cargo.toml
- cli/src/args.rs
- cli/src/command.rs
- src/indexers/any.rs
- src/indexers/electrum_blocking.rs
- src/indexers/esplora_blocking.rs
- src/indexers/mempool_blocking.rs
- src/pay.rs
- src/wallet.rs
- src/wrapper.rs
Part of the epic:
- https://github.com/RGB-WG/rgb-core/pull/263
- https://github.com/RGB-WG/rgb-std/pull/241
- https://github.com/RGB-WG/rgb-interfaces/pull/10
- https://github.com/RGB-WG/rgb-schemata/pull/45
rgb command-line tool if used with `--sync` argument now not just synchronizes the wallet outputs, but also refreshes mining status of witness transactions. We have one additional command-line argument added (`--from-height`) which allows to control from which height the synchronization should start (speeding it up).
> Support new witness filtering

- Cargo.lock
- Cargo.toml
- cli/src/command.rs
- src/indexers/any.rs
- src/indexers/electrum_blocking.rs
- src/indexers/esplora_blocking.rs
- src/indexers/mempool_blocking.rs
- src/lib.rs
- src/pay.rs
- src/wallet.rs
This includes:
- fixes for a deterministic contract state reconstruction (RCP-240731A)
- refactoring of witness processing and indexing
- new way of using interface generics
- contract state introspection op-codes
In order to test this please use 
```toml
[patch.crates-io]
bp-consensus = { git = "https://github.com/BP-WG/bp-core", branch = "master" }
bp-derive = { git = "https://github.com/BP-WG/bp-std", branch = "master" }
bp-invoice = { git = "https://github.com/BP-WG/bp-std", branch = "master" }
descriptors = { git = "https://github.com/BP-WG/bp-std", branch = "master" }
psbt = { git = "https://github.com/BP-WG/bp-std", branch = "master" }
bp-std = { git = "https://github.com/BP-WG/bp-std", branch = "master" }
bp-wallet = { git = "https://github.com/BP-WG/bp-wallet", branch = "master" …
```
> Update to support recent changes in downstream projects

- Cargo.lock
- Cargo.toml
- src/pay.rs
Uses API fix introduced by https://github.com/RGB-WG/rgb-std/pull/265
> Use just single secret seal in payments

- src/indexers/esplora_blocking.rs
Closes https://github.com/RGB-WG/rgb-std/issues/266 by allowing detection of mempool TXs from the esplora indexer. This way electrum and esplora indexers will behave the same.
> esplora indexer: detect mempool TXs

- src/indexers/any.rs
This PR adds the `Send` trait bound to the `inner` field of the `AnyResolver` struct.
Without this change when trying to create an rgb-lib wallet (which contains an instance of `AnyResolver`) in `tokio::task::spawn_blocking` we receive an error, saying that
```
`(dyn rgb::indexers::any::RgbResolver + 'static)` cannot be sent between threads safely
```
This was not happening with beta 5, where `AnyResolver` was an enum
> RgbResolver: add Send trait bound

- .github/workflows/build.yml
- .github/workflows/test.yml
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- src/wallet.rs
This will fix the windows build on the CI by adding nasm as a dependency
> Fix Windows builds in CI

- src/pay.rs
Improves testing verbosity in https://github.com/RGB-WG/rgb-tests/pull/26
> Detect insufficient state early

- src/descriptor.rs
**Description**
Add taproot key in derive method.
> fix: add taproot key only

- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/README.md
- cli/src/args.rs
- cli/src/command.rs
- examples/rgb20-demo.con
- examples/rgb20-demo.yaml
- psbt/src/lib.rs
- psbt/src/rgb.rs
- src/descriptor.rs
- src/errors.rs
- src/filters.rs
- src/indexers/any.rs
- src/indexers/electrum_blocking.rs
- src/indexers/esplora_blocking.rs
- src/indexers/mempool_blocking.rs
- src/lib.rs
- src/pay.rs
This PR is part of a v0.11 fixes epic, see https://github.com/RGB-WG/rgb-tests/pull/30 for an overview.
> Experiments on v0.11

- Cargo.lock
- Cargo.toml
- src/descriptor.rs
RGB wallet descriptor serialization fails with WPKH descriptor types due to `serde_yaml` limitation with nested enums.
```
Persistence error: serializing nested enums in YAML is not supported yet
```
The `RgbDescr` struct contains nested enum structures:
```rust
pub struct RgbDescr<K: DeriveSet = XpubDerivable> {
deriver: RgbDeriver<K>,  // enum containing StdDescr<K> enum
// ...
}
```
When using WPKH descriptors, this creates:
`RgbDeriver::OpretOnly(StdDescr::Wpkh(...))` - a nested enum structure that `serde_yaml` cannot serialize.
Add `singleton_map_recursive` serde attribute to the `deriver` field:
```rust
pub struct RgbDescr<K: DeriveSet = XpubDerivable> {
#[cfg_attr(feature = "serde", serde(with = "serde_yaml::with::singleton_map_recursive"))]
deriver: RgbDeriver<K>,
seals: …
```
> Fix: RGB Descriptor YAML Serialization for Nested Enums
